#!/usr/bin/env bash
# One command for the whole stack — Postgres + backend (:8586) +
# frontend (:8090) — safe to run on a totally fresh clone, safe to run
# again after every `git pull`.
#
#     ./start.sh
#
# First run only: backend/.env and .env (docker-compose.yml's own
# overrides — see its top comment) don't exist yet, so this generates
# them with random values for everything that's safe to invent locally
# (JWT signing secret, Postgres's password, the admin account's
# password) and leaves a clearly-marked blank for everything that
# ISN'T — an AI provider key, an SMS provider's credentials, your own
# phone number — because those are real accounts nobody but you has,
# not secrets that can be conjured. Both files are gitignored (see
# .gitignore) and never touched again once they exist, so editing them
# by hand afterward is always safe — this script will not overwrite
# your changes on the next run.
set -euo pipefail
cd "$(dirname "$0")"

BACKEND_ENV="backend/.env"
ROOT_ENV=".env"

if [ ! -f "$BACKEND_ENV" ]; then
    if [ ! -f "backend/.env.example" ]; then
        echo "FATAL: backend/.env.example is missing — can't generate backend/.env from it." >&2
        exit 1
    fi
    if ! command -v openssl >/dev/null 2>&1; then
        echo "FATAL: openssl is required to generate random secrets (apt install openssl)." >&2
        exit 1
    fi

    echo "No backend/.env — generating one (first run only)."
    cp backend/.env.example "$BACKEND_ENV"

    SECRET_KEY="$(openssl rand -hex 32)"
    ADMIN_PASSWORD="$(openssl rand -base64 18 | tr -dc 'A-Za-z0-9' | cut -c1-16)"

    # The admin account is provisioned at backend startup by main.py's
    # _provision_admin — which returns immediately unless ADMIN_EMAIL is
    # set, and creates an account that CANNOT log in unless ADMIN_PHONE
    # is too (sign-in is phone-only, see schemas.UserLogin). Generating a
    # password without both of these produced exactly that: a printed
    # password belonging to no account at all. Neither value can be
    # invented — the phone has to be a real number that receives SMS —
    # so ask, and only fall back to a warning when there's no terminal
    # to ask from (CI, `docker compose` wrappers, a non-interactive
    # provisioning script).
    ADMIN_PHONE=""
    if [ -t 0 ]; then
        echo
        echo "Admin sign-in is by PHONE, not email. Enter the phone number that"
        echo "should own the admin account, in full international form."
        printf "  Admin phone (e.g. +992901234567), or blank to skip: "
        read -r ADMIN_PHONE
        echo
    fi

    # -i (in place, no backup suffix) — fine on the Linux servers this
    # targets; macOS/BSD sed would need -i '' instead, not handled here
    # since DEPLOY.md's whole deploy path is Ubuntu.
    sed -i "s|^SECRET_KEY=.*|SECRET_KEY=${SECRET_KEY}|" "$BACKEND_ENV"
    sed -i "s|^ADMIN_PASSWORD=.*|ADMIN_PASSWORD=${ADMIN_PASSWORD}|" "$BACKEND_ENV"

    if [ -n "$ADMIN_PHONE" ]; then
        sed -i "s|^ADMIN_PHONE=.*|ADMIN_PHONE=${ADMIN_PHONE}|" "$BACKEND_ENV"
        # _provision_admin keys off the EMAIL, so it has to be non-empty
        # for the account to be created at all — it is never used to log
        # in (phone-only), just as the provisioning key and the address
        # shown in the admin panel. A placeholder on the machine's own
        # hostname is enough and needs nothing from the operator.
        sed -i "s|^ADMIN_EMAIL=.*|ADMIN_EMAIL=admin@$(hostname -f 2>/dev/null || echo localhost)|" "$BACKEND_ENV"
        GENERATED_ADMIN_PASSWORD="$ADMIN_PASSWORD"
    else
        ADMIN_SETUP_SKIPPED=1
    fi
fi

if [ ! -f "$ROOT_ENV" ]; then
    echo "No .env — generating docker-compose's own Postgres password (first run only)."
    POSTGRES_PASSWORD="$(openssl rand -hex 16)"
    cat > "$ROOT_ENV" <<EOF
# Generated by start.sh — see docker-compose.yml's own top comment for
# what these three do. Safe to hand-edit; this script never overwrites
# an existing .env.
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
BACKEND_PORT=8586
FRONTEND_PORT=8090
EOF
fi

docker compose up -d --build

# Only for this final printout — docker-compose.yml itself reads .env
# on its own via Compose's built-in auto-load, this script doesn't need
# these exported for `up` to see them. Sourced here (not just grepped)
# so this stays correct even if .env sets other overrides.
set -a
# shellcheck disable=SC1090
[ -f "$ROOT_ENV" ] && source "$ROOT_ENV"
set +a

echo
echo "========================================================================"
echo "  Frontend:  http://localhost:${FRONTEND_PORT:-8090}"
echo "  Backend:   http://localhost:${BACKEND_PORT:-8586}/api/health"
if [ -n "${GENERATED_ADMIN_PASSWORD:-}" ]; then
    ADMIN_PHONE_SET="$(grep -m1 '^ADMIN_PHONE=' "$BACKEND_ENV" | cut -d= -f2-)"
    echo
    echo "  Admin account created. Sign in at the frontend with:"
    echo
    echo "    Phone:    ${ADMIN_PHONE_SET}"
    echo "    Password: ${GENERATED_ADMIN_PASSWORD}"
    echo
    echo "  SAVE THE PASSWORD NOW — it is only ever shown this once."
    echo
elif [ -n "${ADMIN_SETUP_SKIPPED:-}" ]; then
    echo
    echo "  NO ADMIN ACCOUNT WAS CREATED — no phone number was given, and"
    echo "  sign-in is phone-only, so an account without one cannot log in."
    echo "  To create it: set BOTH of these in backend/.env, then re-run"
    echo "  'docker compose up -d --build':"
    echo "    ADMIN_PHONE=+992901234567     (your real number)"
    echo "    ADMIN_EMAIL=admin@localhost   (any value; just the lookup key)"
    echo "    ADMIN_PASSWORD=...            (already generated, see the file)"
    echo
fi
echo "  Still needed before AI/SMS work — edit backend/.env, then re-run"
echo "  'docker compose up -d --build':"
echo "    AI_API_KEY (..5)       a Cerebras key, or generation fails"
echo "    ROBITA_* or TWILIO_*   an SMS provider, or sign-up codes only"
echo "                           print to 'docker compose logs backend'"
echo "    CORS_ORIGINS           your real domain (only matters for the"
echo "                           mobile app; the website proxies via /api)"
echo "========================================================================"
