#!/usr/bin/env bash
# One command for the whole stack — Postgres + backend (:8586) +
# frontend (:8090) — safe to run on a totally fresh clone, safe to run
# again after every `git pull`.
#
#     ./start.sh
#
# First run only: backend/.env and .env (docker-compose.yml's own
# overrides — see its top comment) don't exist yet, so this generates
# them with random values for everything that's safe to invent locally
# (JWT signing secret, Postgres's password, the admin account's
# password) and leaves a clearly-marked blank for everything that
# ISN'T — an AI provider key, an SMS provider's credentials, your own
# phone number — because those are real accounts nobody but you has,
# not secrets that can be conjured. Both files are gitignored (see
# .gitignore) and never touched again once they exist, so editing them
# by hand afterward is always safe — this script will not overwrite
# your changes on the next run.
set -euo pipefail
cd "$(dirname "$0")"

BACKEND_ENV="backend/.env"
ROOT_ENV=".env"

if [ ! -f "$BACKEND_ENV" ]; then
    if [ ! -f "backend/.env.example" ]; then
        echo "FATAL: backend/.env.example is missing — can't generate backend/.env from it." >&2
        exit 1
    fi
    if ! command -v openssl >/dev/null 2>&1; then
        echo "FATAL: openssl is required to generate random secrets (apt install openssl)." >&2
        exit 1
    fi

    echo "No backend/.env — generating one (first run only)."
    cp backend/.env.example "$BACKEND_ENV"

    SECRET_KEY="$(openssl rand -hex 32)"
    ADMIN_PASSWORD="$(openssl rand -base64 18 | tr -dc 'A-Za-z0-9' | cut -c1-16)"

    # -i (in place, no backup suffix) — fine on the Linux servers this
    # targets; macOS/BSD sed would need -i '' instead, not handled here
    # since DEPLOY.md's whole deploy path is Ubuntu.
    sed -i "s|^SECRET_KEY=.*|SECRET_KEY=${SECRET_KEY}|" "$BACKEND_ENV"
    sed -i "s|^ADMIN_PASSWORD=.*|ADMIN_PASSWORD=${ADMIN_PASSWORD}|" "$BACKEND_ENV"

    GENERATED_ADMIN_PASSWORD="$ADMIN_PASSWORD"
fi

if [ ! -f "$ROOT_ENV" ]; then
    echo "No .env — generating docker-compose's own Postgres password (first run only)."
    POSTGRES_PASSWORD="$(openssl rand -hex 16)"
    cat > "$ROOT_ENV" <<EOF
# Generated by start.sh — see docker-compose.yml's own top comment for
# what these three do. Safe to hand-edit; this script never overwrites
# an existing .env.
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
BACKEND_PORT=8586
FRONTEND_PORT=8090
EOF
fi

docker compose up -d --build

# Only for this final printout — docker-compose.yml itself reads .env
# on its own via Compose's built-in auto-load, this script doesn't need
# these exported for `up` to see them. Sourced here (not just grepped)
# so this stays correct even if .env sets other overrides.
set -a
# shellcheck disable=SC1090
[ -f "$ROOT_ENV" ] && source "$ROOT_ENV"
set +a

echo
echo "========================================================================"
echo "  Frontend:  http://localhost:${FRONTEND_PORT:-8090}"
echo "  Backend:   http://localhost:${BACKEND_PORT:-8586}/api/health"
if [ -n "${GENERATED_ADMIN_PASSWORD:-}" ]; then
    echo
    echo "  Admin account was just created. SAVE THIS PASSWORD NOW — it is"
    echo "  only ever shown this once:"
    echo
    echo "    Password: ${GENERATED_ADMIN_PASSWORD}"
    echo
    echo "  Still needed before login/AI/SMS actually work — edit backend/.env:"
    echo "    ADMIN_PHONE       your real phone number, to log in as this admin"
    echo "    AI_API_KEY (..5)  a Cerebras account key, or material generation fails"
    echo "    ROBITA_* or TWILIO_*   an SMS provider, or codes only print to the"
    echo "                           backend's own logs instead of sending"
    echo
    echo "  After editing backend/.env: docker compose up -d --build (again)."
fi
echo "========================================================================"
